/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApplyRouteImport } from './routes/_app/apply'
import { Route as AppArticlesIndexRouteImport } from './routes/_app/articles/index'
import { Route as AppArticlesSlugRouteImport } from './routes/_app/articles/$slug'
import { Route as AppAuthLoginRouteImport } from './routes/_app/auth/login'
import { Route as AppAuthRegisterRouteImport } from './routes/_app/auth/register'
import { Route as AppAuthVerifyRouteImport } from './routes/_app/auth/verify'
import { Route as AppReviewIndexRouteImport } from './routes/_app/review/index'
import { Route as AppReviewApplicationIdRouteImport } from './routes/_app/review/$applicationId'
import { Route as AppReviewInvitationsRouteImport } from './routes/_app/review/invitations'
import { Route as AppReviewMembersRouteImport } from './routes/_app/review/members'
import { Route as AppReviewProbationRouteImport } from './routes/_app/review/probation'
import { Route as AppReviewPromotionsRouteImport } from './routes/_app/review/promotions'
import { Route as AppWriteIndexRouteImport } from './routes/_app/write/index'
import { Route as AppWriteArticleIdRouteImport } from './routes/_app/write/$articleId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDossierSplatRouteImport } from './routes/api/dossier/$'
import { Route as AppAuthRegisterIndexRouteImport } from './routes/_app/auth/register/index'
import { Route as AppAuthRegisterInvitedRouteImport } from './routes/_app/auth/register/invited'
import { Route as AppAuthRegisterMemberRouteImport } from './routes/_app/auth/register/member'
import { Route as AppAuthRegisterReaderRouteImport } from './routes/_app/auth/register/reader'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyRoute = AppApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesSlugRoute = AppArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRegisterRoute = AppAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthVerifyRoute = AppAuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIndexRoute = AppReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewApplicationIdRoute = AppReviewApplicationIdRouteImport.update({
  id: '/review/$applicationId',
  path: '/review/$applicationId',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewInvitationsRoute = AppReviewInvitationsRouteImport.update({
  id: '/review/invitations',
  path: '/review/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewMembersRoute = AppReviewMembersRouteImport.update({
  id: '/review/members',
  path: '/review/members',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewProbationRoute = AppReviewProbationRouteImport.update({
  id: '/review/probation',
  path: '/review/probation',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewPromotionsRoute = AppReviewPromotionsRouteImport.update({
  id: '/review/promotions',
  path: '/review/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppWriteIndexRoute = AppWriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => AppRoute,
} as any)
const AppWriteArticleIdRoute = AppWriteArticleIdRouteImport.update({
  id: '/write/$articleId',
  path: '/write/$articleId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDossierSplatRoute = ApiDossierSplatRouteImport.update({
  id: '/api/dossier/$',
  path: '/api/dossier/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRegisterIndexRoute = AppAuthRegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthRegisterRoute,
} as any)
const AppAuthRegisterInvitedRoute = AppAuthRegisterInvitedRouteImport.update({
  id: '/invited',
  path: '/invited',
  getParentRoute: () => AppAuthRegisterRoute,
} as any)
const AppAuthRegisterMemberRoute = AppAuthRegisterMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AppAuthRegisterRoute,
} as any)
const AppAuthRegisterReaderRoute = AppAuthRegisterReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => AppAuthRegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/apply': typeof AppApplyRoute
  '/articles/$slug': typeof AppArticlesSlugRoute
  '/auth/login': typeof AppAuthLoginRoute
  '/auth/register': typeof AppAuthRegisterRouteWithChildren
  '/auth/verify': typeof AppAuthVerifyRoute
  '/review/$applicationId': typeof AppReviewApplicationIdRoute
  '/review/invitations': typeof AppReviewInvitationsRoute
  '/review/members': typeof AppReviewMembersRoute
  '/review/probation': typeof AppReviewProbationRoute
  '/review/promotions': typeof AppReviewPromotionsRoute
  '/write/$articleId': typeof AppWriteArticleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dossier/$': typeof ApiDossierSplatRoute
  '/articles/': typeof AppArticlesIndexRoute
  '/review/': typeof AppReviewIndexRoute
  '/write/': typeof AppWriteIndexRoute
  '/auth/register/invited': typeof AppAuthRegisterInvitedRoute
  '/auth/register/member': typeof AppAuthRegisterMemberRoute
  '/auth/register/reader': typeof AppAuthRegisterReaderRoute
  '/auth/register/': typeof AppAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/apply': typeof AppApplyRoute
  '/': typeof AppIndexRoute
  '/articles/$slug': typeof AppArticlesSlugRoute
  '/auth/login': typeof AppAuthLoginRoute
  '/auth/verify': typeof AppAuthVerifyRoute
  '/review/$applicationId': typeof AppReviewApplicationIdRoute
  '/review/invitations': typeof AppReviewInvitationsRoute
  '/review/members': typeof AppReviewMembersRoute
  '/review/probation': typeof AppReviewProbationRoute
  '/review/promotions': typeof AppReviewPromotionsRoute
  '/write/$articleId': typeof AppWriteArticleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dossier/$': typeof ApiDossierSplatRoute
  '/articles': typeof AppArticlesIndexRoute
  '/review': typeof AppReviewIndexRoute
  '/write': typeof AppWriteIndexRoute
  '/auth/register/invited': typeof AppAuthRegisterInvitedRoute
  '/auth/register/member': typeof AppAuthRegisterMemberRoute
  '/auth/register/reader': typeof AppAuthRegisterReaderRoute
  '/auth/register': typeof AppAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/apply': typeof AppApplyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/articles/$slug': typeof AppArticlesSlugRoute
  '/_app/auth/login': typeof AppAuthLoginRoute
  '/_app/auth/register': typeof AppAuthRegisterRouteWithChildren
  '/_app/auth/verify': typeof AppAuthVerifyRoute
  '/_app/review/$applicationId': typeof AppReviewApplicationIdRoute
  '/_app/review/invitations': typeof AppReviewInvitationsRoute
  '/_app/review/members': typeof AppReviewMembersRoute
  '/_app/review/probation': typeof AppReviewProbationRoute
  '/_app/review/promotions': typeof AppReviewPromotionsRoute
  '/_app/write/$articleId': typeof AppWriteArticleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dossier/$': typeof ApiDossierSplatRoute
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/review/': typeof AppReviewIndexRoute
  '/_app/write/': typeof AppWriteIndexRoute
  '/_app/auth/register/invited': typeof AppAuthRegisterInvitedRoute
  '/_app/auth/register/member': typeof AppAuthRegisterMemberRoute
  '/_app/auth/register/reader': typeof AppAuthRegisterReaderRoute
  '/_app/auth/register/': typeof AppAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/articles/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/review/$applicationId'
    | '/review/invitations'
    | '/review/members'
    | '/review/probation'
    | '/review/promotions'
    | '/write/$articleId'
    | '/api/auth/$'
    | '/api/dossier/$'
    | '/articles/'
    | '/review/'
    | '/write/'
    | '/auth/register/invited'
    | '/auth/register/member'
    | '/auth/register/reader'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/apply'
    | '/'
    | '/articles/$slug'
    | '/auth/login'
    | '/auth/verify'
    | '/review/$applicationId'
    | '/review/invitations'
    | '/review/members'
    | '/review/probation'
    | '/review/promotions'
    | '/write/$articleId'
    | '/api/auth/$'
    | '/api/dossier/$'
    | '/articles'
    | '/review'
    | '/write'
    | '/auth/register/invited'
    | '/auth/register/member'
    | '/auth/register/reader'
    | '/auth/register'
  id:
    | '__root__'
    | '/_app'
    | '/_app/apply'
    | '/_app/'
    | '/_app/articles/$slug'
    | '/_app/auth/login'
    | '/_app/auth/register'
    | '/_app/auth/verify'
    | '/_app/review/$applicationId'
    | '/_app/review/invitations'
    | '/_app/review/members'
    | '/_app/review/probation'
    | '/_app/review/promotions'
    | '/_app/write/$articleId'
    | '/api/auth/$'
    | '/api/dossier/$'
    | '/_app/articles/'
    | '/_app/review/'
    | '/_app/write/'
    | '/_app/auth/register/invited'
    | '/_app/auth/register/member'
    | '/_app/auth/register/reader'
    | '/_app/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDossierSplatRoute: typeof ApiDossierSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply': {
      id: '/_app/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AppApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/$slug': {
      id: '/_app/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof AppArticlesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login': {
      id: '/_app/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/register': {
      id: '/_app/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AppAuthRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/verify': {
      id: '/_app/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AppAuthVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/': {
      id: '/_app/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AppReviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/$applicationId': {
      id: '/_app/review/$applicationId'
      path: '/review/$applicationId'
      fullPath: '/review/$applicationId'
      preLoaderRoute: typeof AppReviewApplicationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/invitations': {
      id: '/_app/review/invitations'
      path: '/review/invitations'
      fullPath: '/review/invitations'
      preLoaderRoute: typeof AppReviewInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/members': {
      id: '/_app/review/members'
      path: '/review/members'
      fullPath: '/review/members'
      preLoaderRoute: typeof AppReviewMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/probation': {
      id: '/_app/review/probation'
      path: '/review/probation'
      fullPath: '/review/probation'
      preLoaderRoute: typeof AppReviewProbationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/promotions': {
      id: '/_app/review/promotions'
      path: '/review/promotions'
      fullPath: '/review/promotions'
      preLoaderRoute: typeof AppReviewPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/write/': {
      id: '/_app/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof AppWriteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/write/$articleId': {
      id: '/_app/write/$articleId'
      path: '/write/$articleId'
      fullPath: '/write/$articleId'
      preLoaderRoute: typeof AppWriteArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dossier/$': {
      id: '/api/dossier/$'
      path: '/api/dossier/$'
      fullPath: '/api/dossier/$'
      preLoaderRoute: typeof ApiDossierSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/auth/register/': {
      id: '/_app/auth/register/'
      path: '/'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AppAuthRegisterIndexRouteImport
      parentRoute: typeof AppAuthRegisterRoute
    }
    '/_app/auth/register/invited': {
      id: '/_app/auth/register/invited'
      path: '/invited'
      fullPath: '/auth/register/invited'
      preLoaderRoute: typeof AppAuthRegisterInvitedRouteImport
      parentRoute: typeof AppAuthRegisterRoute
    }
    '/_app/auth/register/member': {
      id: '/_app/auth/register/member'
      path: '/member'
      fullPath: '/auth/register/member'
      preLoaderRoute: typeof AppAuthRegisterMemberRouteImport
      parentRoute: typeof AppAuthRegisterRoute
    }
    '/_app/auth/register/reader': {
      id: '/_app/auth/register/reader'
      path: '/reader'
      fullPath: '/auth/register/reader'
      preLoaderRoute: typeof AppAuthRegisterReaderRouteImport
      parentRoute: typeof AppAuthRegisterRoute
    }
  }
}

interface AppAuthRegisterRouteChildren {
  AppAuthRegisterInvitedRoute: typeof AppAuthRegisterInvitedRoute
  AppAuthRegisterMemberRoute: typeof AppAuthRegisterMemberRoute
  AppAuthRegisterReaderRoute: typeof AppAuthRegisterReaderRoute
  AppAuthRegisterIndexRoute: typeof AppAuthRegisterIndexRoute
}

const AppAuthRegisterRouteChildren: AppAuthRegisterRouteChildren = {
  AppAuthRegisterInvitedRoute: AppAuthRegisterInvitedRoute,
  AppAuthRegisterMemberRoute: AppAuthRegisterMemberRoute,
  AppAuthRegisterReaderRoute: AppAuthRegisterReaderRoute,
  AppAuthRegisterIndexRoute: AppAuthRegisterIndexRoute,
}

const AppAuthRegisterRouteWithChildren = AppAuthRegisterRoute._addFileChildren(
  AppAuthRegisterRouteChildren,
)

interface AppRouteChildren {
  AppApplyRoute: typeof AppApplyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesSlugRoute: typeof AppArticlesSlugRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
  AppAuthRegisterRoute: typeof AppAuthRegisterRouteWithChildren
  AppAuthVerifyRoute: typeof AppAuthVerifyRoute
  AppReviewApplicationIdRoute: typeof AppReviewApplicationIdRoute
  AppReviewInvitationsRoute: typeof AppReviewInvitationsRoute
  AppReviewMembersRoute: typeof AppReviewMembersRoute
  AppReviewProbationRoute: typeof AppReviewProbationRoute
  AppReviewPromotionsRoute: typeof AppReviewPromotionsRoute
  AppWriteArticleIdRoute: typeof AppWriteArticleIdRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
  AppReviewIndexRoute: typeof AppReviewIndexRoute
  AppWriteIndexRoute: typeof AppWriteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplyRoute: AppApplyRoute,
  AppIndexRoute: AppIndexRoute,
  AppArticlesSlugRoute: AppArticlesSlugRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
  AppAuthRegisterRoute: AppAuthRegisterRouteWithChildren,
  AppAuthVerifyRoute: AppAuthVerifyRoute,
  AppReviewApplicationIdRoute: AppReviewApplicationIdRoute,
  AppReviewInvitationsRoute: AppReviewInvitationsRoute,
  AppReviewMembersRoute: AppReviewMembersRoute,
  AppReviewProbationRoute: AppReviewProbationRoute,
  AppReviewPromotionsRoute: AppReviewPromotionsRoute,
  AppWriteArticleIdRoute: AppWriteArticleIdRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
  AppReviewIndexRoute: AppReviewIndexRoute,
  AppWriteIndexRoute: AppWriteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDossierSplatRoute: ApiDossierSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
