/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAuthLoginRouteImport } from './routes/$lang/auth/login'
import { Route as LangAuthRegisterRouteImport } from './routes/$lang/auth/register'
import { Route as LangAuthVerifyRouteImport } from './routes/$lang/auth/verify'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangAuthRegisterMemberRouteImport } from './routes/$lang/auth/register/member'
import { Route as LangAuthRegisterReaderRouteImport } from './routes/$lang/auth/register/reader'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthLoginRoute = LangAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRegisterRoute = LangAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthVerifyRoute = LangAuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => LangRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthRegisterMemberRoute = LangAuthRegisterMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => LangAuthRegisterRoute,
} as any)
const LangAuthRegisterReaderRoute = LangAuthRegisterReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => LangAuthRegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/register': typeof LangAuthRegisterRouteWithChildren
  '/$lang/auth/verify': typeof LangAuthVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/auth/register/member': typeof LangAuthRegisterMemberRoute
  '/$lang/auth/register/reader': typeof LangAuthRegisterReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/register': typeof LangAuthRegisterRouteWithChildren
  '/$lang/auth/verify': typeof LangAuthVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/auth/register/member': typeof LangAuthRegisterMemberRoute
  '/$lang/auth/register/reader': typeof LangAuthRegisterReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/register': typeof LangAuthRegisterRouteWithChildren
  '/$lang/auth/verify': typeof LangAuthVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/auth/register/member': typeof LangAuthRegisterMemberRoute
  '/$lang/auth/register/reader': typeof LangAuthRegisterReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/auth/verify'
    | '/api/auth/$'
    | '/$lang/auth/register/member'
    | '/$lang/auth/register/reader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/auth/verify'
    | '/api/auth/$'
    | '/$lang/auth/register/member'
    | '/$lang/auth/register/reader'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/auth/verify'
    | '/api/auth/$'
    | '/$lang/auth/register/member'
    | '/$lang/auth/register/reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth/login': {
      id: '/$lang/auth/login'
      path: '/auth/login'
      fullPath: '/$lang/auth/login'
      preLoaderRoute: typeof LangAuthLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth/register': {
      id: '/$lang/auth/register'
      path: '/auth/register'
      fullPath: '/$lang/auth/register'
      preLoaderRoute: typeof LangAuthRegisterRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth/verify': {
      id: '/$lang/auth/verify'
      path: '/auth/verify'
      fullPath: '/$lang/auth/verify'
      preLoaderRoute: typeof LangAuthVerifyRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/register/member': {
      id: '/$lang/auth/register/member'
      path: '/member'
      fullPath: '/$lang/auth/register/member'
      preLoaderRoute: typeof LangAuthRegisterMemberRouteImport
      parentRoute: typeof LangAuthRegisterRoute
    }
    '/$lang/auth/register/reader': {
      id: '/$lang/auth/register/reader'
      path: '/reader'
      fullPath: '/$lang/auth/register/reader'
      preLoaderRoute: typeof LangAuthRegisterReaderRouteImport
      parentRoute: typeof LangAuthRegisterRoute
    }
  }
}

interface LangAuthRegisterRouteChildren {
  LangAuthRegisterMemberRoute: typeof LangAuthRegisterMemberRoute
  LangAuthRegisterReaderRoute: typeof LangAuthRegisterReaderRoute
}

const LangAuthRegisterRouteChildren: LangAuthRegisterRouteChildren = {
  LangAuthRegisterMemberRoute: LangAuthRegisterMemberRoute,
  LangAuthRegisterReaderRoute: LangAuthRegisterReaderRoute,
}

const LangAuthRegisterRouteWithChildren =
  LangAuthRegisterRoute._addFileChildren(LangAuthRegisterRouteChildren)

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangAuthLoginRoute: typeof LangAuthLoginRoute
  LangAuthRegisterRoute: typeof LangAuthRegisterRouteWithChildren
  LangAuthVerifyRoute: typeof LangAuthVerifyRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangAuthLoginRoute: LangAuthLoginRoute,
  LangAuthRegisterRoute: LangAuthRegisterRouteWithChildren,
  LangAuthVerifyRoute: LangAuthVerifyRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
